# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa88ca00386f35a95620d93f2143bbfa784a87285d7041d4c8ad4fd08eb04e24168a68ec67a0ab41fae78a7b24e4390b946cd6d1ae76f78512884886554a5ff

test:
  secret_key_base: 243f813bb3c7eb9ca7d8177fc10240a8e3adafd2fd6b2e2a7d8a8266c7aed628e11fc1918a50790078234237ec50b0203263a0ab70116d7b712c6723a4caaf69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
